INSERT INTO AUTOR(ID,NOME,NASCIMENTO)VALUES(1,'PEDRO MENDES', '1980-12-01');
INSERT INTO LIVRO(ID,AUTOR_ID,EDITORA,NOME,PUBLICACAO)VALUES(1,1, 'DOURADOS','COMO PROGRAMAR','2020-04-21');
INSERT INTO LIVRO(ID,AUTOR_ID,EDITORA,NOME,PUBLICACAO)VALUES(2,1, 'MODERNA','SONHO FELIZ','2019-12-21');


